# -*- coding: utf-8 -*-

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPdXOAY8LSL2X2phmWvpvrdmuDQGsHpe
"""

!pip install -U smolagents[toolkit]

!pip install smolagents  # Install smolagents

!pip install --upgrade smolagents  # Update smolagents to the latest version

from smolagents import CodeAgent, DuckDuckGoSearchTool, InferenceClientModel

# Inicialize o modelo
model = InferenceClientModel()

# Inicialize a ferramenta de busca
search_tool = DuckDuckGoSearchTool()

# Crie o agente com a ferramenta de busca
agent = CodeAgent(tools=[search_tool], model=model)

# Execute uma consulta
response = agent.run("Qual a altura do Cristo Redentor?")
print(response)

from smolagents import CodeAgent, DuckDuckGoSearchTool, InferenceClientModel

# Inicialize o modelo
model = InferenceClientModel()

# Inicialize a ferramenta de busca
search_tool = DuckDuckGoSearchTool()

# Crie o agente com a ferramenta de busca
agent = CodeAgent(tools=[search_tool], model=model)

# Execute uma consulta
response = agent.run("Quem foi Ada Lovelace?")
print(response)
